In [1]:
import numpy as np
# for reproducibility
np.random.seed(1)

# Generate random data
ages = np.random.randint(22,40, size = 10)
salaries = np.random.randint(40000, 80000, size = 10)
scores = np.random.randint(60, 100, size = 10)

# combine into a 2d array
data = np.column_stack((ages, salaries, scores))
print("Employee Data (Age, Salary, Score):\n", data)


Employee Data (Age, Salary, Score):
 [[   27 60609    89]
 [   33 47751    74]
 [   34 71228    64]
 [   30 76230    83]
 [   31 72025    83]
 [   33 61758    90]
 [   27 75730    92]
 [   37 48444    82]
 [   22 59946    73]
 [   38 77532    69]]


In [ ]:
print("Avg salary:", np.average(data[:,1]))
print("Avg age:", np.average(data[:,0]))
print("Avg score:", np.average(data[:,2]))
print("Maximum salary:", np.max(data[:,1]))
print("Minimum salary:", np.min(data[:,1]))
print("Std of scores:", np.std(data[:,2]))

Avg salary: 65125.3
Avg age: 31.2
Avg score: 79.9
Maximum salary: 77532
Minimum salary: 47751
Std of scores: 8.99388681271896


In [7]:
high_performers = data[(data[:,1] > 60000) & (data[:,2] > 80)]
print("High Performers:\n", high_performers)


High Performers:
 [[   27 60609    89]
 [   30 76230    83]
 [   31 72025    83]
 [   33 61758    90]
 [   27 75730    92]]


In [11]:
top_salaries_indices = np.argsort(data[:,1])[-3:]  # indices of top 3 salaries
top_salaries = data[top_salaries_indices]
print("Top 3 Salaries:\n", top_salaries)


Top 3 Salaries:
 [[   27 75730    92]
 [   30 76230    83]
 [   38 77532    69]]


In [17]:
new_employee = np.array([[28, 50000, 82]])
data = np.vstack((data, new_employee))
print("Data after adding new employee:\n", data)

Data after adding new employee:
 [[   27 60609    89]
 [   33 47751    74]
 [   34 71228    64]
 [   30 76230    83]
 [   31 72025    83]
 [   33 61758    90]
 [   27 75730    92]
 [   37 48444    82]
 [   22 59946    73]
 [   38 77532    69]
 [   28 50000    82]
 [   28 50000    82]
 [   28 50000    82]]


In [20]:
# Average salary for employees under 30
under_30 = data[data[:,0]<30]
avg_salary_under_30 = np.mean(under_30[:,1])
print("Average salary for employees under 30:",avg_salary_under_30)

Average salary for employees under 30: 57714.166666666664


In [22]:
# Highest score employee:
best_score_employee = data[np.argmax(data[:,2])]
print("Highest score employee is", best_score_employee)

Highest score employee is [   27 75730    92]


In [25]:
# Employees aged between 25-30 with salary > 50000:
subset = data[(data[:,0]>=25)&(data[:,0]<=30)&(data[:,1]>50000)]
print("Employees aged 25-30 with salary > 50k:\n", subset)

Employees aged 25-30 with salary > 50k:
 [[   27 60609    89]
 [   30 76230    83]
 [   27 75730    92]]
